# Generated by Django 5.0.4 on 2025-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_is_featured_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
